# These are supported funding model platforms

github: [iamjaydatt, itisuniqueofficial] # Personal + Organization दोनों usernames
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: itisuniqueofficial
thanks_dev: 
custom: ['https://www.itisuniqueofficial.com/', 'https://razorpay.me/@itisuniqueofficial']
